#!/bin/tcsh

if( -e ppi ) then     #if this file exist

   echo " ppi with 2m_intervals"
   foreach i ( 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16) 
        ibrun ./ppi -n $i <2m_intervals
   end


   echo " ppi with 2b_intervals"

   foreach i ( 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16) 
        ibrun ./ppi -n $i <2b_intervals
   end
endif

